# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: objective-c

env:
  matrix:
    - TEST_SDK=iphonesimulator12.2 OS=12.2 NAME='iPhone X'

cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- gem install slather
- pod repo update
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/Rucksack.xcworkspace -scheme Rucksack-Example -sdk $TEST_SDK ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
